spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb?useUnicode=yes&characterEncoding=UTF-8&time_zone=Asia/Dhaka&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MariaDB10Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 10000
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 200KB
      max-file-size:       500MB
      max-request-size:    500MB

logging:
  file:
    name: customer-service.log
    path: ./logs
